#!/usr/bin/env bash

. `dirname $0`/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
meta_flavor="qux"
flavors="foo baz" # flavors called by meta_flavor

cd $TDIR/

# concatenate flavor build with an additional option
jtest_log info "run cqfd run -c with a given '$meta_flavor' meta_flavor"

for flavor in $flavors bar
do
  test_file=$flavor
  if [ -f "$test_file" ]; then
    jtest_log fatal "$test_file already present before test"
    rm -f $test_file
    continue
  fi
done

jtest_prepare "cqfd run build cmd for '$meta_flavor' meta_flavor"
$cqfd -B $meta_flavor run


for flavor in $flavors
do
  test_file=$flavor
  if ! grep -qw "cqfd" $test_file; then
    jtest_log fatal "$test_file not present after test"
    jtest_result fail
    rm -f $test_file
    fail=set
    continue
  fi
done

test_file=bar
if grep -qw "cqfd" $test_file; then
  jtest_log fatal "$test_file is present after test and shall not"
  jtest_result fail
  rm -f $test_file
  fail=set
  continue
fi

if [ -z $fail ]; then
    jtest_result pass
fi

rm -f $test_file
